<a href="https://colab.research.google.com/github/GovindSingh9447/AI_ML_Notes/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
import numpy as np

In [6]:
a=np.array([1,2,3,4,5])
print(a)
print(type(a))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [7]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [8]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [9]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [10]:
b=np.array([[1,2,3,4,5],[0,9,8,7,6]])
print(b)
print(type(b))

[[1 2 3 4 5]
 [0 9 8 7 6]]
<class 'numpy.ndarray'>


In [11]:
c=np.array([[[1,2,3,4],[4,3,2,1]],[[1,2,3,4],[4,3,2,1]]])
print(c)

[[[1 2 3 4]
  [4 3 2 1]]

 [[1 2 3 4]
  [4 3 2 1]]]


In [12]:
np.random.randint(2,10,5)

array([4, 7, 7, 4, 7])

In [13]:
np.random.randint(20,size=(4,4))

array([[14, 19,  1,  5],
       [ 0, 19, 14, 11],
       [ 0, 15,  9,  0],
       [ 5,  2, 16, 18]])

In [14]:
np.array([1,2,3,4,5],dtype=bool)

array([ True,  True,  True,  True,  True])

In [15]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [16]:
np.arange(0,15,3)

array([ 0,  3,  6,  9, 12])

In [17]:
from numpy import *
a= arange(12)
a=a.reshape(3,2,2)
print(a)

[[[ 0  1]
  [ 2  3]]

 [[ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]]]


In [18]:
#Transposes arr (rows become columns and vice versa)
trans=np.array([(1,2,3,4),(6,7,8,9)])
trans.T

array([[1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

In [19]:
trans.reshape(4,2)

array([[1, 2],
       [3, 4],
       [6, 7],
       [8, 9]])

In [20]:
#Changes arr shape to 6x6 and fills new values with 0
trans.resize((6,6),refcheck=False)
trans

array([[1, 2, 3, 4, 6, 7],
       [8, 9, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

In [21]:
#Returns number of elements in arr
arr=np.array([1,2,3,4,5,6,7,8,9])
arr.size

9

In [22]:
#Appends values to end of arr
arr2=np.append(arr,[0,2,3,5,7])
arr2

array([1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 2, 3, 5, 7])

In [23]:
#Inserts values into arr before index 2
np.insert(arr2,2,4)

array([1, 2, 4, 3, 4, 5, 6, 7, 8, 9, 0, 2, 3, 5, 7])

In [24]:
#Deletes row on index 4 of arr
np.delete(trans,4)

array([1, 2, 3, 4, 7, 8, 9, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [25]:
#Deletes column on index 5 of arr
np.delete(trans,5,axis=1)

array([[1, 2, 3, 4, 6],
       [8, 9, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [26]:
abs(-1)

np.int64(1)

In [27]:
add.accumulate(array([1.,2.,3.,4.]))

array([ 1.,  3.,  6., 10.])

In [28]:
multiply.accumulate(array([1.,2.,5.,8.]))

array([ 1.,  2., 10., 80.])

In [29]:
add.accumulate(array([[1,2,3],[4,5,6]]),axis=0)

array([[1, 2, 3],
       [5, 7, 9]])

In [30]:
add.accumulate(array([[1,2,3],[4,5,6]]),axis=1)

array([[ 1,  3,  6],
       [ 4,  9, 15]])

In [31]:
add(array([-1,3,5]),array([1,3,9]))

array([ 0,  6, 14])

In [32]:
allclose(array([1e10,1e-7]), array([1.00001e10,1e-8]))

False

In [33]:
a = array([True, False, True])
a.all()

np.False_

In [34]:
# in radians
angle(1+1j)

np.float64(0.7853981633974483)

In [35]:
# in degrees
angle(1+1j,deg=True)

np.float64(45.0)

In [36]:
a = array([True, False, True])
a.any()

np.True_

In [37]:
from numpy import *
a = array([10,20,30,40])
append(a,50)

array([10, 20, 30, 40, 50])

In [38]:
array([10, 20, 30, 40, 50])
append(a,[50,60])

array([10, 20, 30, 40, 50, 60])

In [39]:
array([10, 20, 30, 40, 50])
append(a,[59,60])

array([10, 20, 30, 40, 59, 60])

In [40]:
#View documentation for arr.tolist
np.info(arr.tolist)

a.tolist()

Return the array as an ``a.ndim``-levels deep nested list of Python scalars.

Return a copy of the array data as a (nested) Python list.
Data items are converted to the nearest compatible builtin Python type, via
the `~numpy.ndarray.item` function.

If ``a.ndim`` is 0, then since the depth of the nested list is 0, it will
not be a list at all, but a simple Python scalar.

Parameters
----------
none

Returns
-------
y : object, or list of object, or list of list of object, or ...
    The possibly nested list of array elements.

Notes
-----
The array may be recreated via ``a = np.array(a.tolist())``, although this
may sometimes lose precision.

Examples
--------
For a 1D array, ``a.tolist()`` is almost the same as ``list(a)``,
except that ``tolist`` changes numpy scalars to Python scalars:

>>> a = np.uint32([1, 2])
>>> a_list = list(a)
>>> a_list
[1, 2]
>>> type(a_list[0])
<class 'numpy.uint32'>
>>> a_tolist = a.tolist()
>>> a_tolist
[1, 2]
>>> type(a_tolist[0])
<class 'int'

In [41]:
from numpy import *
def myfunc(a): # function works on a 1d arrays, takes the average of the 1st an last element
    return (a[0]+a[-1])/2
b = array([[1,2,3],[4,5,6],[7,8,9]])
apply_along_axis(myfunc,0,b)

array([4., 5., 6.])

In [42]:
from numpy import *
a = arange(24).reshape(2,3,4) # a has 3 axes: 0,1 and 2
a

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [43]:
# sum over all axes except axis=1, result has same shape as original
apply_over_axes(sum, a, [0,2])

array([[[ 60],
        [ 92],
        [124]]])